#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random


# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    T = random.randint(1, 1000)  # TODO: edit here
    N = [None for _ in range(T)]
    M = [None for _ in range(T)]
    A = [None for _ in range(T)]
    B = [None for _ in range(T)]
    for i in range(T):
        N[i] = random.randint(1, 10**9)  # TODO: edit here
        M[i] = random.randint(1, 10**9)  # TODO: edit here
        A[i] = random.randint(1, 10**9)  # TODO: edit here
        B[i] = random.randint(1, 10**9)  # TODO: edit here
    print(T)
    for i in range(T):
        print(N[i], M[i], A[i], B[i])


if __name__ == "__main__":
    main()
